profile2.type.*:
  type: mapping
  label: 'Profile type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'Label'
    registration:
        type: boolean
        label: 'Registration'
    langcode:
      type: string
      label: 'Default language'
